### ISSUE TITLE
EnforceVersionPresenceDisabler is missing from Sitecore 7

### ISSUE THREAD

**Issue by GurliGebis** [SitecoreUnicorn/Rainbow#25] opened 2018-08-15 12:37 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
It fails with an exception when trying to use Unicorn on Sitecore 7.2

**If the current behavior is a bug, please provide the steps to reproduce.**
Install the latest version af Unicorn and Rainbow on Sitecore 7.2, serialize some items, and redeserialize them again, it will fail with an exception about EnforceVersionPresenceDisabler not being found in Sitecore.Kernel

**What is the expected behavior?**
It working :)

**Please mention your Sitecore version, Rainbow version, and if also using Unicorn, your version of that too.**
Sitecore 7.2 (latest version), Rainbow 2.0.1, Unicorn 4.0.4

**Comment by GurliGebis** [comment] 2018-08-15 13:34
We did a rollback, which solves it temporarily.

**Comment by cassidydotdk** [comment] 2018-08-15 14:04
Just committed 78f9a141418310a12d91757a9f3827c8989963af that should allow Rainbow to function as intended, without a hard reference to Sitecore 8.2. I've pushed it to NuGet as `2.0.2-pre1`. I don't have a functional Sitecore 7 on hand, would you mind testing it out quickly?

**Closed** 2018-08-15 15:16 UTC
Labels: enhancement

**Comment by GurliGebis** [comment] 2018-08-16 10:06
Good to hear, thanks :)

**Comment by sarrazinc** [comment] 2018-10-10 20:34
I confirm that this fix (2.0.2-pre1) fixes the serialization issue on Unicorn 4.0.4 with Sitecore 7.5 too.
Any idea when Rainbow 2.0.2 is officially released on nuget?
Many thanks!
